apiVersion: v1
kind: Secret
metadata:
  name: {{ include "awx-netbox-frontend.fullname" . }}-secrets
  labels:
    {{- include "awx-netbox-frontend.labels" . | nindent 4 }}
type: Opaque
data:
  netbox-token: {{ .Values.secrets.netbox.token | b64enc | quote }}
  awx-username: {{ .Values.secrets.awx.username | b64enc | quote }}
  awx-password: {{ .Values.secrets.awx.password | b64enc | quote }}